package com.simpdev.sahmride.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006492)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC9E6FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E2F)
val md_theme_light_secondary = Color(0xFF9F4200)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBCB)
val md_theme_light_onSecondaryContainer = Color(0xFF341100)
val md_theme_light_tertiary = Color(0xFF006874)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF97F0FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFF8FDFF)
val md_theme_light_onBackground = Color(0xFF001F25)
val md_theme_light_surface = Color(0xFFF8FDFF)
val md_theme_light_onSurface = Color(0xFF001F25)
val md_theme_light_surfaceVariant = Color(0xFFDDE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF41474D)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
val md_theme_light_inverseSurface = Color(0xFF00363F)
val md_theme_light_inversePrimary = Color(0xFF8BCEFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006492)
val md_theme_light_outlineVariant = Color(0xFFC1C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF8BCEFF)
val md_theme_dark_onPrimary = Color(0xFF00344E)
val md_theme_dark_primaryContainer = Color(0xFF004B6F)
val md_theme_dark_onPrimaryContainer = Color(0xFFC9E6FF)
val md_theme_dark_secondary = Color(0xFFFFB692)
val md_theme_dark_onSecondary = Color(0xFF562000)
val md_theme_dark_secondaryContainer = Color(0xFF7A3000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBCB)
val md_theme_dark_tertiary = Color(0xFF4FD8EB)
val md_theme_dark_onTertiary = Color(0xFF00363D)
val md_theme_dark_tertiaryContainer = Color(0xFF004F58)
val md_theme_dark_onTertiaryContainer = Color(0xFF97F0FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF001F25)
val md_theme_dark_onBackground = Color(0xFFA6EEFF)
val md_theme_dark_surface = Color(0xFF001F25)
val md_theme_dark_onSurface = Color(0xFFA6EEFF)
val md_theme_dark_surfaceVariant = Color(0xFF41474D)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C7CE)
val md_theme_dark_outline = Color(0xFF8B9198)
val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
val md_theme_dark_inversePrimary = Color(0xFF006492)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF8BCEFF)
val md_theme_dark_outlineVariant = Color(0xFF41474D)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF01A4EB)


//Laila

//
//val md_theme_light_primary = Color(0xFF005FB0)
//val md_theme_light_onPrimary = Color(0xFFFFFFFF)
//val md_theme_light_primaryContainer = Color(0xFFD5E3FF)
//val md_theme_light_onPrimaryContainer = Color(0xFF001C3B)
//val md_theme_light_secondary = Color(0xFF00658E)
//val md_theme_light_onSecondary = Color(0xFFFFFFFF)
//val md_theme_light_secondaryContainer = Color(0xFFC7E7FF)
//val md_theme_light_onSecondaryContainer = Color(0xFF001E2E)
//val md_theme_light_tertiary = Color(0xFF00629F)
//val md_theme_light_onTertiary = Color(0xFFFFFFFF)
//val md_theme_light_tertiaryContainer = Color(0xFFD0E4FF)
//val md_theme_light_onTertiaryContainer = Color(0xFF001D34)
//val md_theme_light_error = Color(0xFFBA1A1A)
//val md_theme_light_errorContainer = Color(0xFFFFDAD6)
//val md_theme_light_onError = Color(0xFFFFFFFF)
//val md_theme_light_onErrorContainer = Color(0xFF410002)
//val md_theme_light_background = Color(0xFFFAFCFF)
//val md_theme_light_onBackground = Color(0xFF001F2A)
//val md_theme_light_surface = Color(0xFFFAFCFF)
//val md_theme_light_onSurface = Color(0xFF001F2A)
//val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
//val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
//val md_theme_light_outline = Color(0xFF74777F)
//val md_theme_light_inverseOnSurface = Color(0xFFE1F4FF)
//val md_theme_light_inverseSurface = Color(0xFF003547)
//val md_theme_light_inversePrimary = Color(0xFFA6C8FF)
//val md_theme_light_shadow = Color(0xFF000000)
//val md_theme_light_surfaceTint = Color(0xFF005FB0)
//val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
//val md_theme_light_scrim = Color(0xFF000000)
//
//val md_theme_dark_primary = Color(0xFFA6C8FF)
//val md_theme_dark_onPrimary = Color(0xFF00315F)
//val md_theme_dark_primaryContainer = Color(0xFF004786)
//val md_theme_dark_onPrimaryContainer = Color(0xFFD5E3FF)
//val md_theme_dark_secondary = Color(0xFF84CFFF)
//val md_theme_dark_onSecondary = Color(0xFF00344C)
//val md_theme_dark_secondaryContainer = Color(0xFF004C6C)
//val md_theme_dark_onSecondaryContainer = Color(0xFFC7E7FF)
//val md_theme_dark_tertiary = Color(0xFF9ACBFF)
//val md_theme_dark_onTertiary = Color(0xFF003355)
//val md_theme_dark_tertiaryContainer = Color(0xFF004A79)
//val md_theme_dark_onTertiaryContainer = Color(0xFFD0E4FF)
//val md_theme_dark_error = Color(0xFFFFB4AB)
//val md_theme_dark_errorContainer = Color(0xFF93000A)
//val md_theme_dark_onError = Color(0xFF690005)
//val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
//val md_theme_dark_background = Color(0xFF001F2A)
//val md_theme_dark_onBackground = Color(0xFFBFE9FF)
//val md_theme_dark_surface = Color(0xFF001F2A)
//val md_theme_dark_onSurface = Color(0xFFBFE9FF)
//val md_theme_dark_surfaceVariant = Color(0xFF43474E)
//val md_theme_dark_onSurfaceVariant = Color(0xFFC3C6CF)
//val md_theme_dark_outline = Color(0xFF8D9199)
//val md_theme_dark_inverseOnSurface = Color(0xFF001F2A)
//val md_theme_dark_inverseSurface = Color(0xFFBFE9FF)
//val md_theme_dark_inversePrimary = Color(0xFF005FB0)
//val md_theme_dark_shadow = Color(0xFF000000)
//val md_theme_dark_surfaceTint = Color(0xFFA6C8FF)
//val md_theme_dark_outlineVariant = Color(0xFF43474E)
//val md_theme_dark_scrim = Color(0xFF000000)
//
//
//val seed = Color(0xFF008CFF)
