package com.example.compose
import androidx.compose.ui.graphics.Color

//val md_theme_light_primary = Color(0xFF265EA7)
val md_theme_light_primary = Color(0,177,248)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD6E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001B3C)
val md_theme_light_secondary = Color(0xFF00668A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC4E7FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2C)
val md_theme_light_tertiary = Color(0xFF6D5E00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFCE365)
val md_theme_light_onTertiaryContainer = Color(0xFF211B00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF341100)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF341100)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF74777F)
val md_theme_light_inverseOnSurface = Color(0xFFFFEDE6)
val md_theme_light_inverseSurface = Color(0xFF552000)
val md_theme_light_inversePrimary = Color(0xFFA8C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF265EA7)
val md_theme_light_outlineVariant = Color(0xFFC4C6CF)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFA8C8FF)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_primaryContainer = Color(0xFF00468A)
val md_theme_dark_onPrimaryContainer = Color(0xFFD6E3FF)
val md_theme_dark_secondary = Color(0xFF7CD0FF)
val md_theme_dark_onSecondary = Color(0xFF00344A)
val md_theme_dark_secondaryContainer = Color(0xFF004C69)
val md_theme_dark_onSecondaryContainer = Color(0xFFC4E7FF)
val md_theme_dark_tertiary = Color(0xFFDEC64C)
val md_theme_dark_onTertiary = Color(0xFF393000)
val md_theme_dark_tertiaryContainer = Color(0xFF524600)
val md_theme_dark_onTertiaryContainer = Color(0xFFFCE365)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF341100)
val md_theme_dark_onBackground = Color(0xFFFFDBCB)
val md_theme_dark_surface = Color(0xFF341100)
val md_theme_dark_onSurface = Color(0xFFFFDBCB)
val md_theme_dark_surfaceVariant = Color(0xFF43474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6CF)
val md_theme_dark_outline = Color(0xFF8E9099)
val md_theme_dark_inverseOnSurface = Color(0xFF341100)
val md_theme_dark_inverseSurface = Color(0xFFFFDBCB)
val md_theme_dark_inversePrimary = Color(0xFF265EA7)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFA8C8FF)
val md_theme_dark_outlineVariant = Color(0xFF43474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF1A457C)
